import numpy as np
# myarr= np.array([5,7,8,6,9])
# # print(type(myarr))
# # print(myarr[0])
# # print(myarr.shape)
# # print(myarr.dtype)
# # y=np.array({1,2,3})
# # print(y,y.dtype)
# # zero=np.zeros(((3,3,3)))
# # print(zero)
# # arr=np.arange(7)
# # print(type(arr))
# # lspace=np.linspace(1,8,4)
# # print(lspace)
# # emp=np.empty((5,5))
# # print(emp)
# emp=np.empty_like(myarr)
# print(emp)
# ide=np.identity(5)
# print(ide)
# arr=np.arange(9)
# print(arr)
# print(arr.reshape((3,3)))
# arr=arr.ravel

